
# This file is automatically generated, you probably don't want to edit this

dichotomousOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dichotomousOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            itotal = TRUE,
            imeasure = TRUE,
            infit = FALSE,
            outfit = FALSE, ...) {

            super$initialize(
                package='Rasch',
                name='dichotomous',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..itotal <- jmvcore::OptionBool$new(
                "itotal",
                itotal,
                default=TRUE)
            private$..imeasure <- jmvcore::OptionBool$new(
                "imeasure",
                imeasure,
                default=TRUE)
            private$..infit <- jmvcore::OptionBool$new(
                "infit",
                infit,
                default=FALSE)
            private$..outfit <- jmvcore::OptionBool$new(
                "outfit",
                outfit,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..itotal)
            self$.addOption(private$..imeasure)
            self$.addOption(private$..infit)
            self$.addOption(private$..outfit)
        }),
    active = list(
        vars = function() private$..vars$value,
        itotal = function() private$..itotal$value,
        imeasure = function() private$..imeasure$value,
        infit = function() private$..infit$value,
        outfit = function() private$..outfit$value),
    private = list(
        ..vars = NA,
        ..itotal = NA,
        ..imeasure = NA,
        ..infit = NA,
        ..outfit = NA)
)

dichotomousResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        items = function() private$.items[["items"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dichotomous Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="items",
                title="Item Statistics",
                visible="(itotal || imeasure || infit || outfit)",
                rows="(vars)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="score", 
                        `title`="total", 
                        `visible`="(itotal)"),
                    list(
                        `name`="measure", 
                        `title`="measure", 
                        `visible`="(imeasure)"),
                    list(
                        `name`="infit", 
                        `title`="infit", 
                        `visible`="(infit)"),
                    list(
                        `name`="outfit", 
                        `title`="outfit", 
                        `visible`="(outfit)"))))}))

dichotomousBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dichotomousBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Rasch',
                name = 'dichotomous',
                version = c(1,0,0),
                options = options,
                results = dichotomousResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Dichotomous Model
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param itotal .
#' @param imeasure .
#' @param infit .
#' @param outfit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$items} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$items$asDF}
#'
#' \code{as.data.frame(results$items)}
#'
#' @export
dichotomous <- function(
    data,
    vars,
    itotal = TRUE,
    imeasure = TRUE,
    infit = FALSE,
    outfit = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dichotomous requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- dichotomousOptions$new(
        vars = vars,
        itotal = itotal,
        imeasure = imeasure,
        infit = infit,
        outfit = outfit)

    analysis <- dichotomousClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
