
# This file is automatically generated, you probably don't want to edit this

dichotomousOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dichotomousOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            pmeasure = TRUE,
            imeasure = TRUE, ...) {

            super$initialize(
                package='rasch',
                name='dichotomous',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..pmeasure <- jmvcore::OptionBool$new(
                "pmeasure",
                pmeasure,
                default=TRUE)
            private$..imeasure <- jmvcore::OptionBool$new(
                "imeasure",
                imeasure,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..pmeasure)
            self$.addOption(private$..imeasure)
        }),
    active = list(
        vars = function() private$..vars$value,
        pmeasure = function() private$..pmeasure$value,
        imeasure = function() private$..imeasure$value),
    private = list(
        ..vars = NA,
        ..pmeasure = NA,
        ..imeasure = NA)
)

dichotomousResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text1 = function() private$.items[["text1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dichotomous Model")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="Dichotomous Model"))}))

dichotomousBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dichotomousBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'rasch',
                name = 'dichotomous',
                version = c(1,0,0),
                options = options,
                results = dichotomousResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Dichotomous Model
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param pmeasure .
#' @param imeasure .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
dichotomous <- function(
    data,
    vars,
    pmeasure = TRUE,
    imeasure = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dichotomous requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- dichotomousOptions$new(
        vars = vars,
        pmeasure = pmeasure,
        imeasure = imeasure)

    analysis <- dichotomousClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
